# Generated by Django 2.2.2 on 2019-07-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='ville',
            new_name='localisation',
        ),
    ]
