# Generated by Django 2.2.2 on 2019-10-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190703_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Localisation',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='localisation',
            new_name='city',
        ),
    ]
