# Generated by Django 2.2.2 on 2019-11-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191017_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='city_lat',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city_lng',
            field=models.CharField(default='FIXME', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city_name',
            field=models.CharField(default='FIXME', max_length=200),
            preserve_default=False,
        ),
    ]
